---
# tasks file for ATLAS

- name: install required packages
  yum: name={{ item }} state=present
  with_items: 
    - gcc
    - gcc-gfortran

- name: check if already installed
  stat: path={{ atlas_prefix }}
  register: atlas_dir
  changed_when: atlas_dir.stat.exists == False

- include: install.yml
  when: atlas_dir.stat.exists == False


